### ISSUE TITLE
Crashes due to C++ assert

### ISSUE THREAD

**Issue by peterurbanec** [lpinner/yardwiz#42]
Downloaded 64 bit Linux version. It asserts on Gentoo x86_64:

```
/tmp/YARDWiz-1.0.0 $ ./yardwiz
./yardwiz:24: wxPyDeprecationWarning: Using deprecated class PySimpleApp.
  wxapp = wx.PySimpleApp(0)
Traceback (most recent call last):
  File "./yardwiz", line 26, in <module>
    wizgui = yardwizgui.GUI()
  File "/tmp/YARDWiz-1.0.0/yardwizgui/__init__.py", line 43, in __init__
    gui.GUI.__init__( self, parent=None )
  File "/tmp/YARDWiz-1.0.0/yardwizgui/gui.py", line 92, in __init__
    self.txtLog.SetMaxLength( 0 )
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 13339, in SetMaxLength
    return _core_.TextEntryBase_SetMaxLength(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "IsSingleLine()" failed at /tmp/portage/x11-libs/wxGTK-3.0.2.0-r1/work/wxPython-src-3.0.2.0/src/gtk/textctrl.cpp(847) in GetEditable(): shouldn't be called for multiline
```

**Comment by lpinner** [comment]
Sorry, my account defaulted to ignoring this repository, so I have only just seen this issue. Will look into it.

**Comment by peterurbanec** [comment]
If I recall correctly, I fixed this by removing the calls to the offending function. There were only a few instances.

**Comment by lpinner** [comment]
It was an issue with the UI builder and wxpython/wxwidgets 3x. I'm still running wx 2.8.
